デフォルトアサイン設定画面の作成
tsuyoshioyama/next-storybook-for-beginners pull request #14
Opened 2024-07-11 05:27 UTC by tsuyoshioyama

- [x] settingディレクトリを作成する
- [x] app/setting/defaultassign/page.tsxの作成
- [x] app/setting/defaultassign/defaultassign.tsxの作成
- [x] app/setting/defaultassign/defaultassign.stories.tsxの作成
- [x] figmaの画面に合わせてレイアウトを整える

キャプチャー
![スクリーンショット 2024-07-11 142435](https://github.com/tsuyoshioyama/next-storybook-for-beginners/assets/174312394/084f6c03-cb94-4cc1-8919-5d16b83365d6)
![スクリーンショット 2024-07-11 142451](https://github.com/tsuyoshioyama/next-storybook-for-beginners/assets/174312394/f0627207-97b4-48a8-a6fa-02767f9411e9)

2024-07-11 05:58 UTC, fox-Taisei-Nakamura requested changes

2024-07-11 05:58 UTC, fox-Taisei-Nakamura commented on app/setting/defaultassign/defaultassign.tsx
> +                  <div>日曜</div>
細かいですが、休日の際はここも赤文字なるように修正してください

2024-07-11 06:44 UTC, tsuyoshioyama commented on app/setting/defaultassign/defaultassign.tsx
> +                  <div>日曜</div>
指摘いただいていた曜日の部分も休日の際は赤文字になるように修正いたしました。

2024-07-12 02:13 UTC, fox-Taisei-Nakamura approved these changes

2024-07-12 02:16 UTC, merged